/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DocumentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import People.MedicalRecord;
import People.People;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author stacyhuang
 */
public class ManagePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientJPanel
     */
    private JPanel jpanel;
    private HospitalEnterprise enterprise;
    private EcoSystem system;
    private People thispeople;
    private ButtonGroup bgroup;
    public ManagePatientJPanel(JPanel jpanel, Enterprise enterprise, EcoSystem system) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.jpanel=jpanel;
        this.enterprise=(HospitalEnterprise)enterprise;
        this.system=system;
        this.thispeople=null;
        setFieldEdible(false);  
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        this.bgroup=new ButtonGroup();
        bgroup.add(no);bgroup.add(yes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientIdfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        birthdayfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        countyfield = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        statefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emergencynamefield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emergencyphonefield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chronicfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        operationfield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pastfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        familyfield = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        operationfieldupdate = new javax.swing.JTextField();
        operationadd = new javax.swing.JButton();
        chronicfieldupdate = new javax.swing.JTextField();
        chronicadd = new javax.swing.JButton();
        pastfieldupdate = new javax.swing.JTextField();
        pastadd = new javax.swing.JButton();
        familyfieldupdate = new javax.swing.JTextField();
        familyadd = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        bloodcombo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        allergyfield = new javax.swing.JTextField();
        allergyfieldupdate = new javax.swing.JTextField();
        allergyadd = new javax.swing.JButton();

        jLabel1.setText("search patient id:");

        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("id");

        jLabel3.setText("name");

        jLabel4.setText("age");

        jLabel5.setText("birthday");

        jLabel6.setText("phone");

        jLabel7.setText("address");

        jLabel8.setText("county");

        jLabel9.setText("state");

        jLabel10.setText("blood");

        jLabel11.setText("emergency name");

        jLabel12.setText("emergency phone");

        jLabel14.setText("chronic disease");

        jLabel15.setText("operation history");

        jLabel16.setText("past history");

        jLabel17.setText("family history");

        jLabel18.setText("pregnancy");

        jLabel19.setText("photo");

        updatebtn.setText("update/create");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        operationadd.setText("add");
        operationadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationaddActionPerformed(evt);
            }
        });

        chronicadd.setText("add");
        chronicadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chronicaddActionPerformed(evt);
            }
        });

        pastadd.setText("add");
        pastadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaddActionPerformed(evt);
            }
        });

        familyadd.setText("add");
        familyadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyaddActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        yes.setText("yes");

        no.setText("no");

        bloodcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--","O","A","B","AB" }));

        jLabel20.setText("gender");

        jLabel21.setText("medicine allergy");

        allergyadd.setText("add");
        allergyadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(250, 250, 250))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(genderfield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(birthdayfield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressfield)
                                    .addComponent(countyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(patientIdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(updatebtn)
                        .addGap(57, 57, 57)
                        .addComponent(savebtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bloodcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emergencynamefield)
                            .addComponent(emergencyphonefield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pastfield, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(familyfield)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(allergyfield))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chronicfield, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(operationfield))))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pastfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pastadd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(familyfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(familyadd)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(operationfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operationadd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chronicfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chronicadd))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allergyfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allergyadd)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(patientIdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(countyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(birthdayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(genderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(operationfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operationadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(chronicfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chronicfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chronicadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(pastfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(familyfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(familyadd))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(familyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allergyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allergyfieldupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergyadd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(yes)
                        .addComponent(no))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(emergencynamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(emergencyphonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bloodcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(savebtn))
                .addGap(122, 122, 122)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        emergencynamefield.setEditable(false);
        emergencyphonefield.setEditable(false);
     
        String searchId=patientIdfield.getText();
        thispeople=null;
        if(searchId.equals("")){
            JOptionPane.showMessageDialog(null, "please enter patient id to search");
            return;
        }else{
            for(People peopleFound:system.getPeopleDirectory().getPeoples()){
                if(peopleFound.getId().equals(searchId)){
                    thispeople=peopleFound;
                    break;
                }
            }
        }
            if(thispeople!=null){
                setField(thispeople.getId(),thispeople.getName(),thispeople.getBirthday(),thispeople.getAge(),thispeople.getPhone(),thispeople.getAddress(),thispeople.getCounty(),thispeople.getState(),thispeople.getPicture(),thispeople.getGender());
                MedicalRecord mr=thispeople.getMedicalRecord();
                setMedicalRecord(mr.getPregancy(),mr.getBloodType(),mr.getEmergency_contactName(),mr.getEmergency_contactPhone(),mr.getPast_history(),mr.getFamily_history(),mr.getOperation_history(),mr.getChronicDisease(),mr.getMedicineAllergy());
                }else{
                JOptionPane.showMessageDialog(null, "cannot find this patient, please make sure the id you enter is correct");
                patientIdfield.setText("");
                return;
            }
              
    }//GEN-LAST:event_searchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        savebtn.setEnabled(true);updatebtn.setEnabled(false);
        
        emergencynamefield.setEditable(true);
        emergencyphonefield.setEditable(true);
        yes.setEnabled(true);no.setEnabled(true);
        bloodcombo.setEnabled(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
        String emergencyname=emergencynamefield.getText();
        String emergencyphone=emergencyphonefield.getText();
        if(emergencyname.equals("")||emergencyphone.equals("")){
            JOptionPane.showMessageDialog(null, "pregnancy field, emergency field cannot be blank");
            return;
        }
   
        try{
            Integer.valueOf(emergencyphone);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "phone must be number");
            emergencyphonefield.setText("");
            return;
        }
        thispeople.getMedicalRecord().setEmergency_contactName(emergencyname);
        thispeople.getMedicalRecord().setEmergency_contactPhone(emergencyphone);
        if(yes.isSelected()){
            thispeople.getMedicalRecord().setPregancy("yes");
        }else{
            thispeople.getMedicalRecord().setPregancy("no");
        }
        if(bloodcombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "please select blood type");
            return;
        }else{
            System.out.println((String)bloodcombo.getSelectedItem());
            thispeople.getMedicalRecord().setBloodType((String) bloodcombo.getSelectedItem());
        }
        JOptionPane.showMessageDialog(null, "create/update success");
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        emergencynamefield.setEditable(false);
        emergencyphonefield.setEditable(false);
        yes.setEnabled(false);no.setEnabled(false);
        bloodcombo.setEnabled(false);
    }//GEN-LAST:event_savebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtnActionPerformed

    private void operationaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationaddActionPerformed
        // TODO add your handling code here:
        String operation=operationfieldupdate.getText();
        if(operation.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getOperation_history().add(operation);
        operationfield.setText(convertArrayToString(thispeople.getMedicalRecord().getOperation_history()));
        operationfieldupdate.setText("");
    }//GEN-LAST:event_operationaddActionPerformed

    private void chronicaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chronicaddActionPerformed
        // TODO add your handling code here:
        String chronic=chronicfieldupdate.getText();
        if(chronic.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getChronicDisease().add(chronic);
        chronicfield.setText(convertArrayToString(thispeople.getMedicalRecord().getChronicDisease()));
        chronicfieldupdate.setText("");
    }//GEN-LAST:event_chronicaddActionPerformed

    private void pastaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaddActionPerformed
        // TODO add your handling code here:
        String past=pastfieldupdate.getText();
        if(past.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getPast_history().add(past);
        pastfield.setText(convertArrayToString(thispeople.getMedicalRecord().getPast_history()));
        pastfieldupdate.setText("");
    }//GEN-LAST:event_pastaddActionPerformed

    private void familyaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyaddActionPerformed
        // TODO add your handling code here:
        String family=familyfieldupdate.getText();
        if(family.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getFamily_history().add(family);
        familyfield.setText(convertArrayToString(thispeople.getMedicalRecord().getFamily_history()));
        familyfieldupdate.setText("");
    }//GEN-LAST:event_familyaddActionPerformed

    private void allergyaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyaddActionPerformed
        // TODO add your handling code here:
        String allergy=allergyfieldupdate.getText();
        if(allergy.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getMedicineAllergy().add(allergy);
        allergyfield.setText(convertArrayToString(thispeople.getMedicalRecord().getMedicineAllergy()));
        allergyfieldupdate.setText("");
    }//GEN-LAST:event_allergyaddActionPerformed
    private void setFieldEdible(boolean boo){
        idfield.setEditable(boo);
        namefield.setEditable(boo);
        birthdayfield.setEditable(boo);
        agefield.setEditable(boo);
        phonefield.setEditable(boo);
        addressfield.setEditable(boo);
        statefield.setEditable(boo);
        countyfield.setEditable(boo);
        emergencynamefield.setEditable(boo);
        emergencyphonefield.setEditable(boo);
        pastfield.setEditable(boo);
        operationfield.setEditable(boo);
        familyfield.setEditable(boo);
        chronicfield.setEditable(boo);
        allergyfield.setEditable(boo);
        yes.setEnabled(boo);
        no.setEnabled(boo);
        bloodcombo.setEnabled(boo);
        genderfield.setEditable(boo);
    }
    private void setField(String id,String name, String birthday,int age,String phone,String address,String county,String state,String picture,String gender){
        idfield.setText(id);
        namefield.setText(name);
        birthdayfield.setText(birthday);
        agefield.setText(String.valueOf(age));
        phonefield.setText(phone);
        addressfield.setText(address);
        statefield.setText(state);
        countyfield.setText(county);
        ImageIcon im=new ImageIcon(picture);
        imageLabel.setIcon(im);
        genderfield.setText(gender);
    }
    private void setMedicalRecord(String pregnancy,String blood,String emergency_name,String emergency_phone,ArrayList<String>past,ArrayList<String>family,ArrayList<String>operation,ArrayList<String>chronic,ArrayList<String>allergy){

        if(blood.equals("")){
            bloodcombo.setSelectedItem("--");
        }else{
            bloodcombo.setSelectedItem(blood);}
        if(pregnancy.equals("yes")){
            yes.setSelected(true);
        }else if(pregnancy.equals("no")){
            no.setSelected(true);
        }else if(pregnancy.equals("")){
            bgroup.clearSelection();
        }
        emergencynamefield.setText(emergency_name);
        emergencyphonefield.setText(emergency_phone);
        pastfield.setText(convertArrayToString(past));
        operationfield.setText(convertArrayToString(operation));
        familyfield.setText(convertArrayToString(family));
        chronicfield.setText(convertArrayToString(chronic));
        allergyfield.setText(convertArrayToString(allergy));
    }
    private String convertArrayToString(ArrayList<String> arr){
        String toReturn="";
        if(arr.size()!=0){
            toReturn=arr.get(0);
            for(int i=1;i<arr.size(); i++){
                toReturn=toReturn+","+arr.get(i);
            }
        }else{
            toReturn="";
        }
        
        return toReturn;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefield;
    private javax.swing.JButton allergyadd;
    private javax.swing.JTextField allergyfield;
    private javax.swing.JTextField allergyfieldupdate;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField birthdayfield;
    private javax.swing.JComboBox<String> bloodcombo;
    private javax.swing.JButton chronicadd;
    private javax.swing.JTextField chronicfield;
    private javax.swing.JTextField chronicfieldupdate;
    private javax.swing.JTextField countyfield;
    private javax.swing.JTextField emergencynamefield;
    private javax.swing.JTextField emergencyphonefield;
    private javax.swing.JButton familyadd;
    private javax.swing.JTextField familyfield;
    private javax.swing.JTextField familyfieldupdate;
    private javax.swing.JTextField genderfield;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField namefield;
    private javax.swing.JRadioButton no;
    private javax.swing.JButton operationadd;
    private javax.swing.JTextField operationfield;
    private javax.swing.JTextField operationfieldupdate;
    private javax.swing.JButton pastadd;
    private javax.swing.JTextField pastfield;
    private javax.swing.JTextField pastfieldupdate;
    private javax.swing.JTextField patientIdfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField statefield;
    private javax.swing.JButton updatebtn;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
