/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.WorkQueue.WorkRequest_documentDoctor;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stacyhuang
 */
public class PatientDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientDetailJPanel
     */
    private JPanel jpanel;
    private String detail;
    private String medicine;
    private String date;
    public PatientDetailJPanel(JPanel jpanel, String date,String detail,String medicine) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.jpanel=jpanel;
        this.detail=detail;
        this.medicine=medicine;
        this.date=date;
        dateLabel.setText("Date: "+date);
        popMedicine();
        diagnosis.setEditable(false);
        diagnosis.setText(detail);
     
    }

    private void popMedicine(){
       DefaultTableModel model = (DefaultTableModel) medicinetable.getModel();
        model.setRowCount(0);
        for (String str:medicine.split(" ")){
            String a=str;
            Object[] row = new Object[2];
            row[0]=a.split(",")[0];
            row[1]=a.split(",")[1];
//              row[0]=a;
//              row[1]=a;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicinetable = new javax.swing.JTable();
        backbtn1 = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diagnosis.setColumns(20);
        diagnosis.setRows(5);
        jScrollPane1.setViewportView(diagnosis);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 169, 445, 92));

        medicinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "type", "amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(medicinetable);
        if (medicinetable.getColumnModel().getColumnCount() > 0) {
            medicinetable.getColumnModel().getColumn(0).setResizable(false);
            medicinetable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 308, 445, 111));

        backbtn1.setBackground(new java.awt.Color(255, 255, 255));
        backbtn1.setText("back");
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });
        add(backbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 72, 169, 36));

        jLabel1.setText("diagnosis detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 147, -1, -1));

        jLabel2.setText("medicine list");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 286, 192, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextArea diagnosis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicinetable;
    // End of variables declaration//GEN-END:variables
}
