/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightDirectory;
import Business.User.Airliner;
import Business.User.Customer;
import UserInterface.ManageAirliner.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author user
 */

public class TravelAgencyJPanel extends javax.swing.JFrame {
private List<Airliner> airlinerlist;
private List<Customer> cuslist;
private FlightDirectory flightDir;
private CustomerDirectory cusDir;
    private AirlinerDirectory airlinerDir;
//private List<String> list;
    /**
     * Creates new form TravelAgencyJPanel
     */
    public TravelAgencyJPanel() throws ParseException {
       airlinerlist=new ArrayList<Airliner>();
       cuslist=new ArrayList<Customer>();
       flightDir = new FlightDirectory();
       cusDir=new CustomerDirectory();
       airlinerDir=new AirlinerDirectory();
        initComponents();
        initialAirliner();
        initialData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Manage Airliner");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Customer Service");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addGap(79, 79, 79)
                .addComponent(jButton3))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        rightPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialAirliner(){
        //String name, String nationality, int age, String address, int phone
        Airliner airliner0 = new Airliner("Aloha Airline","Taiwan",23, "Jupiter","8573341577");
        Airliner airliner1=new Airliner("Cooooo Airline","China", 40, "41 Mars Street, Wuhan", "0921041875");
        Airliner airliner2=new Airliner("RichardTang Airline","American", 21, "85 Peterborough, Boston, MA","6175150701");
        Airliner airliner3=new Airliner("Bambo Airline","Ireland",91,"80 Long Wood,Ireland","79201000232");
        Airliner airliner4=new Airliner("Star Airline","Tailand",8,"114442, Pad Thi, Baoleen","1947303553");
        
        //AirlinerDirectory air=new AirlinerDirectory();
        airlinerDir.setAirlinerlist(airlinerlist);
        airlinerlist.add(airliner4);
        airlinerlist.add(airliner3);
        airlinerlist.add(airliner2);
        airlinerlist.add(airliner1);
        airlinerlist.add(airliner0);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
          
        ManageAirlinersJPanel panel=new ManageAirlinersJPanel  (rightPanel,airlinerDir,flightDir);
        rightPanel.add("AirlinerManagePanel", panel);
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        rightPanel.add(new CustomerJPanel(rightPanel,flightDir,cusDir,airlinerDir));
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void initialData() throws ParseException{
        
        //name,nationality,age,address,phone
        Customer cus=new Customer("stacy","taiwan",22,"143 park","123");
        cus.setFlightnumber("a123");cus.setSeat("A1"); cus.setID("A");
        
        Customer cus1_2=new Customer("stacy","taiwan",22,"143 park","123");
        cus1_2.setFlightnumber("b123");cus1_2.setSeat("D3");cus1_2.setID("A");
        
        Customer cus1_3=new Customer("stacy","taiwan",22,"143 park","123");
        cus1_3.setFlightnumber("a789");cus1_3.setSeat("F5");cus1_3.setID("A");
        
        Customer cus2=new Customer("emily","japan",49,"111 park","456");
        cus2.setID("B");cus2.setFlightnumber("a123");
        cus2.setSeat("A4");
        Customer cus2_2=new Customer("emily","japan",49,"111 park","456");
        cus2_2.setID("B");cus2_2.setFlightnumber("a789");cus2_2.setSeat("C1");
        
        Customer cus3=new Customer("joesph","boston",22,"1 beacon","111");
        cus3.setID("C");cus3.setFlightnumber("a123");cus3.setSeat("D3");
        
        Customer cus4=new Customer("eric","boston",19,"143 park","654");
        cus4.setID("D");cus4.setFlightnumber("b123");cus4.setSeat("B5");
        Customer cus4_2=new Customer("eric","boston",19,"143 park","654");
        cus4_2.setID("D");cus4_2.setFlightnumber("c123");cus4_2.setSeat("E2");
        
        Customer cus5=new Customer("brian","taiwan",22,"2 westland","532");
        cus5.setID("E");cus5.setFlightnumber("b123");cus5.setSeat("C6");
        Customer cus5_3=new Customer("brian","taiwan",22,"2 westland","532");
        cus5_3.setID("E");cus5_3.setFlightnumber("a456");cus5_3.setSeat("H5");
        Customer cus5_4=new Customer("brian","taiwan",22,"2 westland","532");
        cus5_4.setID("E");cus5_4.setFlightnumber("a789");cus5_4.setSeat("I3");
      
        
        cusDir.setCustomerlist(cuslist);
        cuslist.add(cus);cuslist.add(cus1_2);cuslist.add(cus1_3);cuslist.add(cus2);cuslist.add(cus2_2);
        cuslist.add(cus3);cuslist.add(cus4);cuslist.add(cus4_2);
        cuslist.add(cus5);cuslist.add(cus5_3);cuslist.add(cus5_4);
        
        //System.out.println(cuslist.get(1).getID()+cuslist.get(1).getFlightnumber()+cuslist.get(1).getSeat());

        List<String> list=new ArrayList<String>();
        list.add("Aa");list.add("B");list.add("C");
        Flight flight1 = flightDir.addflight();
        flight1.setAirliner("Aloha Airline");
        flight1.setEstimation("null");
        flight1.setFlightnumber("a123");
        flight1.setID(list);
        flight1.setFrom("boston");
        flight1.setTo("taipei");
        flight1.setFromtime(LocalTime.of(6,30,0));
        flight1.setTotime(LocalTime.of(10, 30, 0));
        String s1="11/03/2020";
        SimpleDateFormat f1=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d1=f1.parse(s1);
        String s2="12/03/2020";
        SimpleDateFormat f2=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d2=f2.parse(s2);
        flight1.setFromdate(d1);
        flight1.setTodate(d2);
        
        List<String> list2=new ArrayList<String>();
        list2.add("A");list2.add("D");list2.add("E");
        Flight flight2 = flightDir.addflight();
        flight2.setAirliner("Aloha Airline");
        flight2.setEstimation("null");
        flight2.setFlightnumber("b123");
        flight2.setID(list);
        flight2.setFrom("boston");
        flight2.setTo("new york");
        flight2.setFromtime(LocalTime.of(14,30,0));
        flight2.setTotime(LocalTime.of(17, 15, 0));
        String s3="27/02/2020";
        SimpleDateFormat f3=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d3=f3.parse(s3);
        String s4="27/02/2020";
        SimpleDateFormat f4=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d4=f4.parse(s4);
        flight2.setFromdate(d3);
        flight2.setTodate(d4);
        
        List<String> list3=new ArrayList<String>();
        list3.add("D");list3.add("D");
        Flight flight3 = flightDir.addflight();
        flight3.setAirliner("Aloha Airline");
        flight3.setEstimation("null");
        flight3.setFlightnumber("c123");
        flight3.setID(list);
        flight3.setFrom("chicago");
        flight3.setTo("montreal");
        flight3.setFromtime(LocalTime.of(16,00,0));
        flight3.setTotime(LocalTime.of(21, 30, 0));
        String s5="19/02/2020";
        SimpleDateFormat f5=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d5=f5.parse(s5);
        String s6="19/02/2020";
        SimpleDateFormat f6=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d6=f6.parse(s6);
        flight3.setFromdate(d5);
        flight3.setTodate(d6);
        
        List<String> list4=new ArrayList<String>();
        list4.add("E");list4.add("E");
        Flight flight4 = flightDir.addflight();
        flight4.setAirliner("Bambo Airline");
        flight4.setEstimation("null");
        flight4.setFlightnumber("a456");
        flight4.setID(list);
        flight4.setFrom("boston");
        flight4.setTo("england");
        flight4.setFromtime(LocalTime.of(1,15,0));
        flight4.setTotime(LocalTime.of(11, 30, 0));
        String s7="19/03/2020";
        SimpleDateFormat f7=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d7=f7.parse(s7);
        String s8="20/03/2020";
        SimpleDateFormat f8=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d8=f8.parse(s8);
        flight4.setFromdate(d7);
        flight4.setTodate(d8);
        
        List<String> list5=new ArrayList<String>();
        list5.add("E");list5.add("A");list5.add("B");
        Flight flight5 = flightDir.addflight();
        flight5.setAirliner("Star Airline");
        flight5.setEstimation("null");
        flight5.setFlightnumber("a789");
        flight5.setID(list);
        flight5.setFrom("boston");
        flight5.setTo("thailand");
        flight5.setFromtime(LocalTime.of(3,30,0));
        flight5.setTotime(LocalTime.of(13, 30, 0));
        String s9="11/05/2020";
        SimpleDateFormat f9=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d9=f9.parse(s9);
        String s10="12/05/2020";
        SimpleDateFormat f10=new SimpleDateFormat("dd/MM/yyyy"); 
        Date d10=f10.parse(s10);
        flight5.setFromdate(d9);
        flight5.setTodate(d10);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TravelAgencyJPanel().setVisible(true);
                } catch (ParseException ex) {
                    System.out.println("date error!");
                    Logger.getLogger(TravelAgencyJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
