/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InvestigationRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InvestigationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.QuarantineRelatedCase;
import Business.WorkQueue.WorkRequest_quarantineList;
import Business.WorkQueue.WorkRequest_receptionInvestigation;
import People.People;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author stacyhuang
 */
public class CreateRelatedCaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvestigationWorkAreaJPanel
     */
    private JPanel jpanel;
    private InvestigationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private WorkRequest_quarantineList RequesttoRecord;
    private People relatedPeople;
    public CreateRelatedCaseJPanel(JPanel jpanel, UserAccount userAccount, InvestigationOrganization organization, Enterprise enterprise, EcoSystem system,WorkRequest_quarantineList RequesttoRecord) {
        initComponents();
        this.jpanel = jpanel;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system=system;
        this.RequesttoRecord=RequesttoRecord;
        createbtn.setEnabled(false);
        popMainTable();
        popRelated();
         //pnChart.setLayout(new BorderLayout());
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     private DefaultCategoryDataset createDataset() {
        // same dataset for line chart and bar chart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "products", "1970");
        dataset.addValue(30, "products", "1980");
        dataset.addValue(60, "products", "1990");
        dataset.addValue(120, "products", "2000");
        dataset.addValue(240, "products", "2010");
        dataset.addValue(300, "products", "2014");

        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        relatedCasetable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        createbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        countyfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        statefield = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        relatedCasetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Case Number", "ID", "Name", "State", "Address", "Phone", "related case number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(relatedCasetable);
        if (relatedCasetable.getColumnModel().getColumnCount() > 0) {
            relatedCasetable.getColumnModel().getColumn(0).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(1).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(2).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(3).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(4).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(5).setResizable(false);
            relatedCasetable.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 960, 183));

        jLabel1.setText("Case:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 27, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 22, 147, -1));

        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });
        add(createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 275, 196, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel6.setText("Phone:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel7.setText("State:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 48, -1));

        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));
        add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 216, -1));

        jLabel9.setText("County:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        countyfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countyfieldActionPerformed(evt);
            }
        });
        add(countyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 216, -1));
        add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 430, 180, -1));
        add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 470, 180, -1));

        jLabel10.setText("Photo:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "case number", "ID", "name", "age", "state", "diagnosis date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setResizable(false);
            mainTable.getColumnModel().getColumn(1).setResizable(false);
            mainTable.getColumnModel().getColumn(2).setResizable(false);
            mainTable.getColumnModel().getColumn(3).setResizable(false);
            mainTable.getColumnModel().getColumn(4).setResizable(false);
            mainTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 960, 90));

        jLabel11.setText("search ID");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 30));
        add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 179, -1));

        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));
        add(statefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 220, -1));
        add(pictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 180, 120));

        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));
        add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 179, -1));

        jLabel12.setText("Gender:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));
        add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 179, -1));

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void popMainTable(){
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        model.setRowCount(0);
        Object[] row=new Object[6];
        row[0]=RequesttoRecord;
        row[1]=RequesttoRecord.getPatient().getId();
        row[2]=RequesttoRecord.getPatient().getName();
        row[3]=RequesttoRecord.getPatient().getAge();
        row[4]=RequesttoRecord.getPatient().getState();
        row[5]=formatter.format(RequesttoRecord.getDiagnosisDate());
        model.addRow(row);
    }
    private void popRelated(){
        DefaultTableModel model = (DefaultTableModel) relatedCasetable.getModel();
        model.setRowCount(0);
        for(QuarantineRelatedCase related:RequesttoRecord.getRelatedCase()){
            Object[] row=new Object[7];
            row[0]=related.getCaseNumber();
            row[1]=related.getQuarantinePeople().getId();
            row[2]=related.getQuarantinePeople().getName();
            row[3]=related.getQuarantinePeople().getState();
            row[4]=related.getQuarantinePeople().getAddress();
            row[5]=related.getQuarantinePeople().getPhone();
            row[6]=related.getRelatedCaseNumber();
            model.addRow(row);
        }
    }
    private void setSearchField(People people){
        namefield.setText(people.getName());
        phonefield.setText(people.getPhone());
        agefield.setText(String.valueOf(people.getAge()));
        genderfield.setText(people.getGender());
        addressfield.setText(people.getAddress());
        statefield.setText(people.getState());
        countyfield.setText(people.getCounty());
        ImageIcon im=new ImageIcon(people.getPicture());
        pictureLabel.setIcon(im);
    }
    private void countyfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countyfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countyfieldActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        this.relatedPeople=null;
        String searchId=searchfield.getText();
        System.out.println("search:"+searchId);
        if(searchId.equals("")){
            JOptionPane.showMessageDialog(null,"please enter");
            return;
        }else{
            for(People p:system.getPeopleDirectory().getPeoples()){
                System.out.println("find id:"+p.getId());
                if(p.getId().equals(searchId)){
                    System.out.println("found!");
                    setSearchField(p);
                    relatedPeople=p;
                    
                    break;
                }
            }
        }
        if(relatedPeople==null){
            JOptionPane.showMessageDialog(null, "no people found");
            return;
        }else{
            createbtn.setEnabled(true);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        QuarantineRelatedCase related=new QuarantineRelatedCase();
        boolean boo=true;
        for(QuarantineRelatedCase r:RequesttoRecord.getRelatedCase()){
            if(relatedPeople.getId().equals(r.getQuarantinePeople().getId())){
                boo=false;
                break;
            }
        }
        if(boo==true){
            related.setQuarantinePeople(relatedPeople);
            int c=system.getCaseCount()+1;
            System.out.println("in create related case:"+c);
            related.setCaseNumber(c);
            related.setRelatedCaseNumber(RequesttoRecord.getCaseNumber());
            RequesttoRecord.getRelatedCase().add(related);
            popRelated();
            System.out.println("reported size:"+RequesttoRecord.getRelatedCase().size());
        }else{
            JOptionPane.showMessageDialog(null, "already add to list");
            return;
        }
    }//GEN-LAST:event_createbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefield;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField countyfield;
    private javax.swing.JButton createbtn;
    private javax.swing.JTextField genderfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable mainTable;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JTable relatedCasetable;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JTextField statefield;
    // End of variables declaration//GEN-END:variables
}
