/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InvestigationRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InvestigationOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.Organization.ReceptionOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.QuarantineRelatedCase;
import Business.WorkQueue.WorkRequest_investigationPolice;
import Business.WorkQueue.WorkRequest_quarantineList;
import People.People;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ManageQuarantineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageQuarantineJPanel
     */
    private JPanel jpanel;
    private InvestigationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private QuarantineRelatedCase relatedCase;
    public ManageQuarantineJPanel(JPanel jpanel, UserAccount userAccount, InvestigationOrganization organization, Enterprise enterprise, EcoSystem system) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.jpanel = jpanel;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system=system;
        setCombo();
        popTable();
        setFieldEdible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setFieldEdible(boolean boo){
        phonefield.setEditable(boo);
        agefield.setEditable(boo);
        statefield.setEditable(boo);
        countyfield.setEditable(boo);
        genderfield.setEditable(boo);
        addressfield.setEditable(boo);
    }
    public void setCombo(){
        networkJComboBox.removeAllItems();
        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }
    public void setEnterprise(Network network){
        enterpriseTypeJComboBox.removeAllItems();
        for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
            if(e.getEnterpriseType().getValue().equals("Police")){
                enterpriseTypeJComboBox.addItem(e);
            }
        }
    }
    private void popTable(){
        DefaultTableModel model = (DefaultTableModel) quarantineTable.getModel();
        model.setRowCount(0);
        for(WorkRequest_quarantineList request:organization.getWorkQueue_quarantineList().getWorkRequestList()){
            for(QuarantineRelatedCase relate:request.getRelatedCase()){
                Object[] row=new Object[8];
                row[0]=relate;
                row[1]=relate.getQuarantinePeople().getId();
                row[2]=relate.getQuarantinePeople().getName();
                row[3]=relate.getQuarantinePeople().getState();
                row[4]=relate.getQuarantinePeople().getPhone();
                row[5]=relate.getRelatedCaseNumber();
                row[6]=relate.getStartdate();
                row[7]=relate.getStatus();
                model.addRow(row);
            }
        }
    }
    
    private void popDetailTable(ArrayList<String> list){
        DefaultTableModel model = (DefaultTableModel) detailTable.getModel();
        model.setRowCount(0);
        for(String str:list){
            Object[] row=new Object[1];
            row[0]=str;
            model.addRow(row);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        quarantineTable = new javax.swing.JTable();
        pictureLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startdate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enddate = new javax.swing.JLabel();
        okbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        selectbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        statefield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        countyfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messagearea = new javax.swing.JTextArea();
        backbtn2 = new javax.swing.JButton();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quarantineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Case Number", "ID", "Name", "State", "Phone", "Related Case Number", "creation date", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(quarantineTable);
        if (quarantineTable.getColumnModel().getColumnCount() > 0) {
            quarantineTable.getColumnModel().getColumn(0).setResizable(false);
            quarantineTable.getColumnModel().getColumn(1).setResizable(false);
            quarantineTable.getColumnModel().getColumn(2).setResizable(false);
            quarantineTable.getColumnModel().getColumn(3).setResizable(false);
            quarantineTable.getColumnModel().getColumn(4).setResizable(false);
            quarantineTable.getColumnModel().getColumn(5).setResizable(false);
            quarantineTable.getColumnModel().getColumn(6).setResizable(false);
            quarantineTable.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1160, 200));

        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(pictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 190));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 60, 40));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 130, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("StartDate");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 230, 30));

        startdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 230, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EndDate");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 230, 30));

        enddate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enddate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 230, 70));

        okbtn.setText("OK");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        add(okbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 200, 50));

        reportbtn.setText("Report To Police");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });
        add(reportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 170, 50));

        selectbtn.setText("select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });
        add(selectbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, -1, -1));

        jLabel6.setText("phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, -1));

        jLabel8.setText("age");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, -1));

        jLabel11.setText("gender");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));
        add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 200, -1));

        jLabel12.setText("address");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));
        add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 200, -1));

        jLabel13.setText("state");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));
        add(statefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 200, -1));

        jLabel14.setText("county");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));
        add(countyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 200, -1));

        jLabel15.setText("message");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        messagearea.setColumns(20);
        messagearea.setRows(5);
        jScrollPane3.setViewportView(messagearea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 210, 80));

        backbtn2.setBackground(new java.awt.Color(255, 255, 255));
        backbtn2.setText("back");
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn2ActionPerformed(evt);
            }
        });
        add(backbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 159, -1));

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, 159, -1));

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "update detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(detailTable);
        if (detailTable.getColumnModel().getColumnCount() > 0) {
            detailTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 340, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        // TODO add your handling code here:
        int select=quarantineTable.getSelectedRow();
        if(select<0){
            JOptionPane.showMessageDialog(null,"please select");
            return;
        }else{
            QuarantineRelatedCase getList=(QuarantineRelatedCase) quarantineTable.getValueAt(select, 0);
            this.relatedCase=getList;
            People p=getList.getQuarantinePeople();
            phonefield.setText(p.getPhone());
            agefield.setText(String.valueOf(p.getAge()));
            statefield.setText(p.getState());
            countyfield.setText(p.getCounty());
            genderfield.setText(p.getGender());
            addressfield.setText(p.getAddress());
            ImageIcon im=new ImageIcon(p.getPicture());
            pictureLabel.setIcon(im);
            startdate.setText(getList.getStartdate());
            enddate.setText(getList.getEnddate());
            if(getList.getDetails()!=null){
                popDetailTable(getList.getDetails());
            }
        }
    }//GEN-LAST:event_selectbtnActionPerformed

    private void backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn2ActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtn2ActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO add your handling code here:
        if(relatedCase.getStatus().equals("under recording")){
            JOptionPane.showMessageDialog(null, "already under recording");
            return;
        }else if(relatedCase.getStatus().equals("sent to Police")){
            JOptionPane.showMessageDialog(null, "already sent to police");
            return;
        }else if(relatedCase.getStatus().equals("pending")){
            relatedCase.setStatus("under recording");
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            Date date=new Date();
            relatedCase.getDetails().add(formatter.format(date)+":under recording");
        }
        if(relatedCase.getDetails()!=null){
                popDetailTable(relatedCase.getDetails());
            }
        popTable();
        
    }//GEN-LAST:event_okbtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        // TODO add your handling code here:
        if(relatedCase.getStatus().equals("sent to Police")){
            JOptionPane.showMessageDialog(null, "already sent to Police Department");
            return;
        }else if(relatedCase.getStatus().equals("pending")){
            JOptionPane.showMessageDialog(null, "you cannot process now, list need to be recorded");
            return;
        }else if(relatedCase.getStatus().equals("under recording")){
             Enterprise en=(Enterprise) enterpriseTypeJComboBox.getSelectedItem();
            if(en==null){
                JOptionPane.showMessageDialog(null, "please select");
                return;
            }else{
            relatedCase.setStatus("sent to Police");
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            Date date=new Date();
            relatedCase.getDetails().add(formatter.format(date)+":send to police");
            if(relatedCase.getDetails()!=null){
                popDetailTable(relatedCase.getDetails());
            }
            String message=messagearea.getText();
            WorkRequest_investigationPolice sendToPolice=new WorkRequest_investigationPolice();
            sendToPolice.setStatus("pending");
            sendToPolice.setMessage(message);
            sendToPolice.setStartdate(relatedCase.getStartdate());
            sendToPolice.setEnddate(relatedCase.getEnddate());
            sendToPolice.setQuarantinePeople(relatedCase.getQuarantinePeople());
            PoliceOrganization policeorg=null;
           
            for(Organization o:en.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof PoliceOrganization){
                    policeorg=(PoliceOrganization) o;
                    break;
                }
            }
            policeorg.getWorkQueue_investigationPolice().getWorkRequestList().add(sendToPolice); 
            JOptionPane.showMessageDialog(null, "sent to police organization");
            messagearea.setText("");
            popTable();
            }
        }
    }//GEN-LAST:event_reportbtnActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        Network network=(Network)networkJComboBox.getSelectedItem();
        if(network!=null){
            setEnterprise(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefield;
    private javax.swing.JButton backbtn2;
    private javax.swing.JTextField countyfield;
    private javax.swing.JTable detailTable;
    private javax.swing.JLabel enddate;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JTextField genderfield;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messagearea;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton okbtn;
    private javax.swing.JTextField phonefield;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JTable quarantineTable;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton selectbtn;
    private javax.swing.JLabel startdate;
    private javax.swing.JTextField statefield;
    // End of variables declaration//GEN-END:variables
}
