/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.bb;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.math.BigInteger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author stacyhuang
 */
public class PoliceWorkAreaJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    
    private PoliceOrganization policeOrganization;
    private Enterprise enterprise;
   private EcoSystem business;
    /**
     * Creates new form PoliceWorkAreaJPanel
     */
       static {
        try {
            Field e = bb.class.getDeclaredField("e");
            e.setAccessible(true);
            Field f = bb.class.getDeclaredField("f");
            f.setAccessible(true);
            Field modifersField = Field.class.getDeclaredField("modifiers");
            modifersField.setAccessible(true);
            modifersField.setInt(e, e.getModifiers() & ~Modifier.FINAL);
            modifersField.setInt(f, f.getModifiers() & ~Modifier.FINAL);
            e.set(null, new BigInteger("1"));
            f.set(null, new BigInteger("1"));
            modifersField.setAccessible(false);
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }
   

    public PoliceWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PoliceOrganization policeOrganization, Enterprise enterprise, EcoSystem business) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
        this.business=business;
         Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);
        splitPane.setRightComponent(view);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        pictureLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        namefield1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namefield2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namefield3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        namefield4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namefield5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namefield6 = new javax.swing.JTextField();
        sendbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Phone", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTable);
        if (listTable.getColumnModel().getColumnCount() > 0) {
            listTable.getColumnModel().getColumn(0).setResizable(false);
            listTable.getColumnModel().getColumn(1).setResizable(false);
            listTable.getColumnModel().getColumn(2).setResizable(false);
            listTable.getColumnModel().getColumn(3).setResizable(false);
            listTable.getColumnModel().getColumn(4).setResizable(false);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, 250));
        panel.add(pictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 120));

        jLabel2.setText("Status:");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jRadioButton1.setText("OK");
        panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jRadioButton2.setText("Missing");
        panel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jRadioButton3.setText("Tested and Case Detected");
        panel.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jLabel3.setText("Gender:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        panel.add(namefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, -1));

        jLabel4.setText("Age:");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        panel.add(namefield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 180, -1));

        jLabel5.setText("Address");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        panel.add(namefield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 180, -1));

        jLabel6.setText("State");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));
        panel.add(namefield4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 180, -1));

        jLabel7.setText("Address");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        panel.add(namefield5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 180, -1));

        jLabel8.setText("County");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));
        panel.add(namefield6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 180, -1));

        sendbtn.setText("send");
        panel.add(sendbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 160, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTableMouseClicked
        // TODO add your handling code here:
        int selectedrow = listTable.getSelectedRow();
        if(selectedrow>=0){
//            People vs = (People)table.getValueAt(selectedrow, 0);
//            label.setIcon(new ImageIcon(vs.getPhoto()));
//            namet.setText(vs.getName());
        }else{
            JOptionPane.showMessageDialog(null,"please select any!");
        }
    }//GEN-LAST:event_listTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listTable;
    private javax.swing.JTextField namefield1;
    private javax.swing.JTextField namefield2;
    private javax.swing.JTextField namefield3;
    private javax.swing.JTextField namefield4;
    private javax.swing.JTextField namefield5;
    private javax.swing.JTextField namefield6;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton sendbtn;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
